version: '3'

services:
  fastfeet-nodejs:
    container_name: fastfeet-nodejs
    build: '.'
    entrypoint: ['./init.sh']
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - fastfeet-postgres
      # - jobs-gympoint
    networks:
      - app-connect
    ports:
      - '3333:3333'

  fastfeet-postgres:
    container_name: fastfeet-postgres
    image: postgres:11
    volumes:
      - fastfeet-postgres-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect
    ports:
      - '5432:5432'


volumes:
  fastfeet-postgres-data:
  # redis-gympoint-data:

networks:
  app-connect:
      driver: bridge
